apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slackernews
  namespace: helmvm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
# needs values that are set in the slackernews-replicated HelmChart CR
spec:
  project: default
  source:
    chart: slackernews-mackerel/unstable/slackernews
    repoURL: registry.shortrib.io
    targetRevision: 0.5.207
    helm:
      values: |
        postgres:
          deploy_postgres: true 

        admin-console:
          adminConsole:
            password: nicely-formally-helped-kingfish

        ingress:
          annotations: 
            kubernetes.io/tls-acme: "true"
            ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
          enabled: true
          ingressClassName: contour

        service:
          type: ClusterIP
          tls:
            enabled: true
            existingSecretName: news.shortrib.app-tls

        slack:
          existingSecretName: slackernews-slack
          existingSecretBotTokenKey: botToken
          existingSecretUserTokenKey: userToken
          existingSecretClientIdKey: clientId
          existingSecretClientSecretKey: clientSecret

        slackernews:
          domain: news.shortrib.app
  destination:
    namespace: slackernews
    server: https://raccoon.lab.shortrib.net:6443
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
