apiVersion: batch/v1
kind: Job
metadata:
  name: preflight-check
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      initContainers:
      - name: format-credentials
        image: nixery.dev/shell/jq
        command:
        - bash
        - -c
        - |
          jq -r '.bearerToken' /var/run/secrets/argocd.io/cluster/config > /var/run/secrets/slackernews.io/cluster/token
          jq -r '.tlsClientConfig.caData | @base64d' /var/run/secrets/argocd.io/cluster/config > /var/run/secrets/slackernews.io/cluster/ca.crt
        volumeMounts:
        - mountPath: /var/run/secrets/argocd.io/cluster
          name: argo-cluster-credentials
          readOnly: true
        - mountPath: /var/run/secrets/slackernews.io/cluster
          name: cluster-credentials
      containers:
      - name: check
        image: replicated/preflight
        env:
        - name: HOME
          value: /home/preflight
        command:
        - bash
        - -c 
        - |
          # little bit of a hack since the exit code for `preflight` is not an indicator
          # as to whether there were any failures
          helm template oci://registry.shortrib.io/slackernews-mackerel/unstable/slackernews | preflight --interactive=false --format json \
            --server https://raccoon.lab.shortrib.net:6443 --certificate-authority /var/run/secrets/slackernews.io/cluster/ca.crt \
            --token $(cat /var/run/secrets/slackernews.io/cluster/token) | grep -q "fail"
          # since we looked for failure, we need to invert the result by comparing to 0
          test $? -ne 0 
          exit $?
        volumeMounts:
        - mountPath: /home/preflight/.docker
          name: registry-credentials
          readOnly: true
        - mountPath: /var/run/secrets/slackernews.io/cluster
          name: cluster-credentials
      volumes:
      - name: registry-credentials
        secret:
          secretName: preflight-registry-credentials
          items:
          - key: .dockerconfigjson
            path: config.json
      - name: argo-cluster-credentials
        secret:
          secretName: cluster-raccoon.lab.shortrib.net-689020247
      - name: cluster-credentials
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
