apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: slackernews
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: About self-hosted retro tool aimed at helping remote teams

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
