apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slackernews-secrets
  namespace: helmvm
spec:
  project: default
  source:
    repoURL: https://github.com/crdant/slackernews-argo-application.git
    targetRevision: fix/first-runthrough
    path: secrets
  destination:
    namespace: slackernews
    server: https://raccoon.lab.shortrib.net:6443
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
