apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slackernews-parent
  namespace: helmvm
spec:
  project: default
  source:
    repoURL: https://github.com/crdant/slackernews-argo-application.git
    targetRevision: fix/first-runthrough
    path: application
  destination:
    namespace: helmvm
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
