apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slackernews-postgresql
  namespace: slackernews
spec:
  encryptedData:
    password: AgCUQunHEWcBjZmXZPUViRapbCju4QU6HVtEd5F/ZgIAw0xj8sQLGnMsj2On/I9DXN9eaeWOCiMGXpmw+uZPqxBNP86LubjPBnF3XQsifFFl9N1r3T/tE4uz+9v8ExL8PdCRf8sXKrbHuCykzdxFVyKLoPKRoEvKvqEHZlvYzLa9hTiQex9LLMsNzaa4XJonGBN3BunssEx71wBbww93CNr6x2X4FvE++85tWRGqgqCfY3QkgAXLh9HNDTxX8jpD4+4viiMxNbCsyZE7FZR3+Ww+boaWS1h6+fFN6rFTQqeOoZP5UarSkqmhDpSL/A9Glu5UpJgv+SsbvWqvRL5d9GAz72P/UlJpAfytvhJpdqxmGg8O3IPMeCzSCA68iH8xvgUeyCp7wv9Sj5VHSpIXcxv9FODpIwtKtzwQX6FEz3PO5Mre98G9oMdOp49p5jWg/0a9FSa7AStEqM0LQhjSuVnArRHcgq0papRsgxoEojKGt5qGv/Cno+YjjrCTYb4DSE6CHUNwtUFXRwYb7QbbDJWowBSWSFTMZwsAjtyfhfjRwmr0IXgQ47V+jc2ENK8l/8hjVIP3VMKENMGCMJLtcqKNKKG6HjE7N/hFxEhkVssF3oUiKxzxi44ow8OxNNiFN2bBZAVos3ptVwtbL6WDl8cUzzNkTp0sHmWbxXmxq4oldUmga0RYjjA29gVimKWVXZnA8BGyKgL7aopZ/XGJXXMZi9UeU5E6yss=
    postgres-password: AgCADPOgM+CqYXbPJ9gm9mz1t8SgztgvxzpK5S4KBsNjGD7P+CUJzzXcu9Fr7zixL/ShFJO7ZHuhaBBASD4YunAmENoXewJbIVqi4VqNgEWvS/03dZGIGPoCH5dVpojkvit0csmZGFyjCVBKmkjNGAXJoYoXXlCilEF7LtGW+IHQJh1BSvJ3FXYpIB8fYA89akNGmeI4mBvUWdx7klUulJsLLjk7PXp7Jhm8EYE3hfE2/mIIPaOx7vltKMztiyGE/StHrZ8ddl3zdWRWgJBtAvLHH8AbCZyKhrZLTR+NvpcARJRpnjuWAc2DkCuVASzE/6mXXhlQktqr9v2tkgBPWjimXIIu0Ma3pemiEGMEXCCh7vyTF5Uv4Io6R9HIYL4tmGRGvN08Qcm2ylw0UT+u/shurBsbxP3MkI3QfcCpyTkVBN/cTfHAUFxx2XTBDHdBaFv42KQKYK3/JLjl7gxNpif19UAgrPWC9dsWcIQTtLghsFIz2S85XdxQcis2aDp6fFo+rL3HHvAeN+fRUoFmpfY0cg2Y1TgQm2ayTiRv++4WQhiKi3ooSuFA2xQlazjeMIdWthKin4f5qfoYJ90H/sOnG+Cv1oDtU3uoNAlElAxsgR10VXAqwzQzKUn5zayP57gcB6YKoHN5PxiA4GJGMVAI4grdMprhuHUZlc2H8Uexruw81YjZhMiyqppD9sfY8GAaWRzo6Y9RL5h0h/uB3RxybbZGDPzp
  template:
    metadata:
      creationTimestamp: null
      name: slackernews-postgresql
      namespace: slackernews

